### ISSUE TITLE
[Bug] Deleting or changing classification of an already trimmed layer breaks the MultiMask

### ISSUE THREAD

**Issue by mradamcox** [ohmg-dev/OldInsuranceMaps#169]
**Describe the problem**
A fairly straight-forward issue: the layer names are saved to the volume in the multimask JSON. If one of them is removed, or reclassified, then the mask interface breaks.

**Expected behavior**
The mask for a layer should be automatically (and safely) removed whenever a layer has been assigned away from that mask.

**Additional context**
See #168

**Comment by rchampine** [comment]
Here is a another instance of this bug — https://oldinsurancemaps.net/loc/sanborn00556_010/. I foolishly walked into it trying to correct a trimming issue on a sheet. Is there a way to salvage the multimask for this volume?

**Comment by mradamcox** [comment]
Yeah, it can definitely be salvaged, just will take a little mucking around on my end to handle the trimming stuff and then remove the entries from the multimask. Can you link the sheets you were trying to fix?

**Comment by rchampine** [comment]
Yep — this one: https://oldinsurancemaps.net/resource/14100. It was initially split into 5 pieces but it should have been 6. This is a low priority issue — we have plenty of other maps to work on.
