### ISSUE TITLE
New sign in on mobile; page expands to too wide

### ISSUE THREAD

**Issue by mradamcox** [ohmg-dev/OldInsuranceMaps#17]
When you sign in on mobile from the home page, some element of the home page is too wide, causing the top navbar to expand which hides the ride-side hamburger menu behind an sideways scroll.

When you navigate away from the home page and then return to it this issue does not occur (the navbar appears as it should) leading me to think it may have to do with the width of the successful sign in alert box... so this is the fist place to look.

**Comment by mradamcox** [comment]
Seeing this in firefox on android, but not in firefox on desktop with the dev tools used to mock a the mobile view.

**Comment by BNAndras** [comment]
For what it's worth, I can't replicate the layout issue on Firefox or Safari on iOS. I do see the long successful login message bar though.

**Comment by mradamcox** [comment]
this has since been fixed.
