### ISSUE TITLE
Load Volume button does not work for Amarillo, Texas | 1955 | Vol. 2 (parser can't handle missing sheet from upstream)

### ISSUE THREAD

**Issue by rchampine** [ohmg-dev/OldInsuranceMaps#171]
https://oldinsurancemaps.net/loc/sanborn08403_007/

The button is clickable but seems to "time out" after a few seconds without loading sheets. This was happened for two different users.

**Comment by rchampine** [comment]
The Load Volume button is currently working on other volumes, however.

**Comment by mradamcox** [comment]
Will check this presently. Looks like the button is available even if you aren't logged in (that's a regression I will need to fix), so make sure that you are logged in when you try.

**Comment by rchampine** [comment]
For sure — confirmed logged in, still not working.

**Comment by rchampine** [comment]
Got it — I'll mark this one as "On Hold" for DSL tracking purposes.

**Comment by mradamcox** [comment]
I reported this issue and looks like they have fixed the LOC resource. You can try loading this volume again. We may as well leave this ticket open until I can have another look at the parser though, maybe get an error message to the frontend or something.

**Comment by rchampine** [comment]
Tried loading again but still getting the same non-functioning response.

**Comment by mradamcox** [comment]
Fixed now. Ultimately, after the problem was fixed in the LOC source record, the saved version of that record did not get updated until I deleted the volume and re-imported it. Something to keep in mind for the improved import process that is in the works.
