### ISSUE TITLE
Forbidden 403 — CSRF Verification failed on login

### ISSUE THREAD

**Issue by rchampine** [ohmg-dev/OldInsuranceMaps#172]
Some DSL students are getting this 403 message when logging in. Clearing the browser cookies is a successful workaround. We have only encountered this on Chrome so far.
![image](https://github.com/mradamcox/ohmg/assets/136510277/0532c745-aee4-4f46-90bc-6afbe2f96b7d)

**Comment by mradamcox** [comment]
It's possible this would be solved by upgrading allauth to 0.55.2 https://github.com/pennersr/django-allauth/releases/tag/0.55.2, which would include this commit: https://github.com/pennersr/django-allauth/pull/3390/files.

I suppose this must be a regression from putting the sign-in form into a modal, unfortunately.

**Comment by mradamcox** [comment]
@rchampine I've made that allauth upgrade, let me know if this issue comes up again.

**Comment by rchampine** [comment]
Sounds good — thanks!

**Comment by mradamcox** [comment]
@rchampine has anyone encountered this recently?
