### ISSUE TITLE
Classify layer as Key Map does not save succesfully

### ISSUE THREAD

**Issue by rchampine** [ohmg-dev/OldInsuranceMaps#178]
I'm not sure if this is just on this map or others as well, but the Classify Layers function is not behaving correctly for saving a Key Map. It appears to work, but upon refreshing or opening up a georeferencing session, the classified sheet reverts back to Main Content. 

https://github.com/mradamcox/ohmg/assets/136510277/3e28346f-2921-45c5-a81d-6117ae3728ad

**Comment by mradamcox** [comment]
Thanks @rchampine, I think I see the problem, should be able to deploy a fix later tonight (as well as some a few other updates).

**Comment by rchampine** [comment]
Great — thank you!

**Comment by rchampine** [comment]
Looks like this issue or a very similar issue is cropping up again.

https://github.com/ohmg-dev/OldInsuranceMaps/assets/136510277/fd9b9ce6-9edd-435e-95d1-47dde8b26866

**Comment by rchampine** [comment]
Additional example on this Philadelphia volume where a map is "stuck" as classified as a Key map: https://oldinsurancemaps.net/resource/32830 
<img width="564" alt="image" src="https://github.com/ohmg-dev/OldInsuranceMaps/assets/136510277/648037c3-1e56-497d-9d07-92ff27fa290f">

**Comment by mradamcox** [comment]
Weirdly, I was able to just go in and classify this one properly right now. There must be some intermittent issue having to do with the state of the page. Definitely warrants investigation.

**Comment by rchampine** [comment]
Interesting... I'm having no luck with reloading and classifying on either of these volumes:
https://oldinsurancemaps.net/map/sanborn04023_022
https://oldinsurancemaps.net/map/sanborn06671_013

**Comment by mradamcox** [comment]
Huh, and again, worked fine for me. Things are a little jumpy sometimes though, like I set to Key Map and it flashed back a forth once or twice and then settles. One thing to note is that the save happens immediately on the dropdown change, not when the Done button is clicked. At any rate, will look further soon.

**Comment by rchampine** [comment]
This volume is also experiencing the bug for both Nate and I — https://oldinsurancemaps.net/map/sanborn09345_008

**Comment by rchampine** [comment]
Great — thank you!

**Comment by mradamcox** [comment]
Ok, I've reworked the process a bit, so the Save/Cancel buttons are implemented again, and the logic that handles the process is a bit cleaner. I think this particular issue should be addressed, though there are still some details to come back to.

**Comment by rchampine** [comment]
Is this implemented publicly? I'm still seeing the same behavior/bug as before.

**Comment by mradamcox** [comment]
:facepalm: Ok _now_ it is.

**Comment by rchampine** [comment]
Yes! Haha thank you.

**Comment by rchampine** [comment]
This problem seems to be happening again on this volume: https://oldinsurancemaps.net/map/sanborn08356_023

**Comment by mradamcox** [comment]
I'm guessing it has to do with the fact that there is a layer currently processing on the volume. Try again when there is no processing and see if the designation sticks then. Either way, thanks for mentioning and I've re-opened this ticket.

**Comment by rchampine** [comment]
Hmm I'm still not having any luck with changing it's classification.

**Comment by mradamcox** [comment]
Ok thanks, I'll fix this this weekend.
