### ISSUE TITLE
Undo preparation button disabled

### ISSUE THREAD

**Issue by rchampine** [ohmg-dev/OldInsuranceMaps#181]
The "undo this determination" button is un-clickable for this sheet. It needs to be reset and split.
https://oldinsurancemaps.net/resource/19762
![image](https://github.com/mradamcox/ohmg/assets/136510277/bed22484-7d51-44ef-a34b-f06ad0a1bcfa)

**Comment by mradamcox** [comment]
Looks to be fixed now.
