### ISSUE TITLE
Georeferenced maps are not showing up in the mosaic preview and main layer

### ISSUE THREAD

**Issue by samyogaa** [ohmg-dev/OldInsuranceMaps#185]
When I georeference, the maps are saved but don't show up in the main layer or mosaic preview. I am able to go back and edit them as well. However, when I move to georeference another sheet, the previously saved ones don't show up. I have attached the links to the volumes and a couple of sheets for your reference, as well as a snapshot of the mosaic preview.

Volume Link: https://oldinsurancemaps.net/map/sanborn07905_040

Map Links (p 1124, p1125, p 1126): 
https://oldinsurancemaps.net/resource/32719
https://oldinsurancemaps.net/resource/32721

![Bug](https://github.com/ohmg-dev/OldInsuranceMaps/assets/167255763/8714c48b-c642-4689-b56c-05066b175820)

**Comment by mradamcox** [comment]
@samyogaa Good catch, I have an idea of what's going on here, and it definitely needs attention. Thanks for filing this!

**Comment by mradamcox** [comment]
Ok, this should be fixed now and all layers that weren't properly assigned are handled. Who you mind poking around a bit, and closing this if everything seems to be working ok?
