### ISSUE TITLE
Saving mulitmask exits full screen and requires page refresh to continue working

### ISSUE THREAD

**Issue by rchampine** [ohmg-dev/OldInsuranceMaps#187]
The mulitmask save button is working but causes the site to exit full screen view, which is disruptive to workflow. After saving, the  mosaic preview and multimask viewers are greyed out and appear to be broken. Refreshing the page at this stage is a successful work around.

https://github.com/ohmg-dev/OldInsuranceMaps/assets/136510277/a8a0079d-acc8-4aa7-ab5e-f3543fd10b2d

**Comment by mradamcox** [comment]
This should be fixed now.
