### ISSUE TITLE
Saving control points and gereferencing document is unusually slow

### ISSUE THREAD

**Issue by rchampine** [ohmg-dev/OldInsuranceMaps#191]
The process of saving control points is usually very fast but as of right now it's extremely sluggish or possibly non-responsive. Perhaps this will resolve itself but I figured I report an issue as multiple students have noticed this over the weekend.

<img width="734" alt="image" src="https://github.com/ohmg-dev/OldInsuranceMaps/assets/136510277/9b37ef4a-4bd2-405d-91b3-c2fa2a15c038">

**Comment by mradamcox** [comment]
Logs show there is something wrong with the POST methods that begin this process. Will look further into it.

**Comment by mradamcox** [comment]
This is now fixed. It was a configuration issue on the server that happened after a maintenance reboot last night.
