### ISSUE TITLE
Load Volume button missing after last update

### ISSUE THREAD

**Issue by rchampine** [ohmg-dev/OldInsuranceMaps#194]
The load volume button appears to be missing after the most recent update. It is possible to click the "Load Volume" text, which changes it to "_Loading sheet X/XX_" but that does not appear to actually load any sheets.
<img width="1624" alt="image" src="https://github.com/ohmg-dev/OldInsuranceMaps/assets/136510277/cf03b475-3c71-4a80-bcf8-0d2ce8c07aaa">

**Comment by mradamcox** [comment]
Ok, the button actually  is still there, I just forgot to add the new CSS class to it so it only looks like text (oops). So clicking it will do the same thing as before. Will address the loading issue through the other ticket.
