### ISSUE TITLE
[Bug] Incomplete volume loads

### ISSUE THREAD

**Issue by mradamcox** [ohmg-dev/OldInsuranceMaps#197]
**Describe the problem**
After I found that new Orleans 1951 Vol. 2 had not been fully loaded, and fixed that in a somewhat messy way, I checked through all other volumes and found a few others that will need some attention:

```
Grand Rapids, Mich. | 1953 | Vol. 7 sanborn04023_023
expected: 73
loaded: 72
Grand Rapids, Mich. | 1953 | Vol. 5 sanborn04023_021
expected: 62
loaded: 61
Kansas City, Mo. | 1951 | Vol. 5 sanborn04720_022
expected: 92
loaded: 73
```

**Comment by mradamcox** [comment]
@rchampine, Just a heads up, there is something more strange going on with the `Grand Rapids, Mich. | 1953 | Vol. 5 sanborn04023_021` item, so I've put a request through the LOC website about it, hopefully that will help get it sorted out.

**Comment by rchampine** [comment]
Got it — thanks!
