### ISSUE TITLE
[Bug] Multiple duplicate "no split" prep sessions are created sometimes

### ISSUE THREAD

**Issue by mradamcox** [ohmg-dev/OldInsuranceMaps#207]
**Describe the problem**
While doing some cleanup on the production database, I noticed there are a lot of duplicate preparation sessions for some documents--34 documents had more than one prep session, usually just two, but one had 33 sessions!

In every case these were "no split needed" preparations, and they were created practically simultaneously. I think there is a bug/glitch with the workflow for this process that sometimes creates duplicates.

**Expected behavior**
Only on prepsession should exist per document, and there should be no way that a second one is created.

**Additional context**
This should be handled with the new database model, but the front-end may also need some work--if there is a redirect or bug causing these duplicates, that could now turn into an ugly error.

**Comment by rchampine** [comment]
I think I found something related to this. It is possible to accidentally create duplicates of a sheet by clicking the "no split needed" button on a sheet summary page. See [here](https://oldinsurancemaps.net/region/26947) for example.

**Comment by mradamcox** [comment]
Interesting, I see the duplicates, and I see that the button styles still look like it it is getting clicked when you click on it (even though it is "greyed" out), however, when I click on it I'm not actually making new documents... This is definitely different from the original ticket here, but certainly a bug and may as well track it here too.

**Comment by mradamcox** [comment]
Ok, I've removed those buttons from the "resource detail" pages (as they are now in the map overview page--more convenient), and added another layer of checks to ensure a document isn't prepared twice.
