### ISSUE TITLE
Page Not Found for preparing key maps

### ISSUE THREAD

**Issue by rchampine** [ohmg-dev/OldInsuranceMaps#213]
For two 1950 Buffalo volumes (and I suspect possibly all of them), clicking Prepare on the key maps leads to Page Not Found. It is possible to prepare other sheets, however.

Volume summary pages:
https://oldinsurancemaps.net/loc/sanborn05793_027/
https://oldinsurancemaps.net/loc/sanborn05793_028/

Page Not Found:
https://oldinsurancemaps.net/split/51665/
https://oldinsurancemaps.net/split/51783/

**Comment by mradamcox** [comment]
Thanks, and sorry about that. Likely a disconnect with the new data model. Will get to this this weekend.

**Comment by rchampine** [comment]
No worries at all! Thanks.

**Comment by rchampine** [comment]
For reference we're seeing it on some other volumes as well: 
https://oldinsurancemaps.net/loc/sanborn03985_075/
https://oldinsurancemaps.net/loc/sanborn03985_076/

**Comment by mradamcox** [comment]
This is most likely due to the fact that the new loading methods assign 0 as a page number to docs that don't have an easy-to-guess page number, which in turn adds 0 within the slug for the document, and that causes a mismatch with the existing ones. This strategy should probably be re-evaluated, but also this particular issue will go away when the migration to the new models is complete overall.

**Comment by jpole1** [comment]
All the following links are to volumes that have a duplicative Page 0 (that remains unprepared) and Title Page/Key Map (that is prepared and georeferenced)

https://oldinsurancemaps.net/map/sanborn03376_010
https://oldinsurancemaps.net/map/sanborn00656_056
https://oldinsurancemaps.net/map/sanborn09064_007
https://oldinsurancemaps.net/map/sanborn05793_030
https://oldinsurancemaps.net/map/sanborn08803_009
https://oldinsurancemaps.net/map/sanborn03985_071
https://oldinsurancemaps.net/map/sanborn05793_029
https://oldinsurancemaps.net/map/sanborn06671_016
https://oldinsurancemaps.net/map/sanborn06671_015
https://oldinsurancemaps.net/map/sanborn05793_028
https://oldinsurancemaps.net/map/sanborn05793_032
https://oldinsurancemaps.net/map/sanborn05793_033
https://oldinsurancemaps.net/map/sanborn09345_002
https://oldinsurancemaps.net/map/sanborn03985_076
https://oldinsurancemaps.net/map/sanborn03985_049
https://oldinsurancemaps.net/map/sanborn05793_027
https://oldinsurancemaps.net/map/sanborn03985_070
https://oldinsurancemaps.net/map/sanborn08803_011
