### ISSUE TITLE
[Bug] Control Points not saved after "Give me more time" prompt 

### ISSUE THREAD

**Issue by rchampine** [ohmg-dev/OldInsuranceMaps#219]
Students have been reporting that some of the control points they place aren't being saved — but I couldn't determine why for a while. Today I ran into this issue after I worked on a couple sheets for a long period and clicked "yes" on the "more time" prompt. The sheets I worked on did not appear as "locked" after finishing the georeferncing page and did not update. It seems like georeferencing work is not actually being saved after that popup. I don't have any further documentation. This is a bit of a hazy guess of a bug report.

**Comment by mradamcox** [comment]
@rchampine This is definitely a significant regression after the latest data model update, as I needed to reconfigure how the session expiration system was handled, and it seems like they are not being extended properly. What I will this evening is just change the default session length to make it much longer (making it take longer for the popup to appear) and hopefully that will reduce the number of times this causes people to lose work. Hopefully I can fix the bug within the next few days too.

**Comment by mradamcox** [comment]
This should now be fixed, and I set the session length back to 10 minutes.
