### ISSUE TITLE
[Request] Double-click layer to zoom volume map overview

### ISSUE THREAD

**Issue by BNAndras** [ohmg-dev/OldInsuranceMaps#55]
**Describe the feature or enhancement you're looking for**
In the overview map's layer list, a double-click on a layer should zoom to that layer's extent as if it were a bookmark. Otherwise, the user has to cross-reference the layer names with the layer thumbnails if they want to change layer order.

**Comment by mradamcox** [comment]
Closing this ticket now, as layers are no longer listed individually in the overview map.
